### PR TITLE
Remove atom-space-pen-views

### PR DESCRIPTION
**Pull request by as-cii**
This pull request replaces atom-space-pen-views with etch and, where appropriate, also manual DOM manipulation. Feature-wise nothing should change, but this will help remove jQuery from Atom.

/cc: @ungb for 👀

### CODE REVIEW

**Comment by ungb** [comment]
I'm getting the following error installing `language-markdown` with this enabled.  Works fine when I apm unlink setting-view from your branch.


**Atom**: 1.14.2 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.2
**Thrown From**: [settings-view](https://github.com/atom/settings-view) package 0.247.0


### Stack Trace

Uncaught NotFoundError: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.

```
At /Users/bungdonuts/github/packages/jqueryTest/settings-view/lib/package-detail-view.js:107

Error: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at Error (native)
    at PackageDetailView.completeInitialzation (/packages/jqueryTest/settings-view/lib/package-detail-view.js:107:35)
    at PackageDetailView.loadPackage (/packages/jqueryTest/settings-view/lib/package-detail-view.js:124:12)
    at /packages/jqueryTest/settings-view/lib/package-detail-view.js:382:14
    at Function.module.exports.Emitter.simpleDispatch (/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/app.asar/node_modules/event-kit/lib/emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (/Users/bungdonuts/github/atom/out/app/node_modules/settings-view/lib/package-manager.coffee:449:14)
    at /Users/bungdonuts/github/atom/out/app/node_modules/settings-view/lib/package-manager.coffee:342:10
    at exit (/Users/bungdonuts/github/atom/out/app/node_modules/settings-view/lib/package-manager.coffee:62:7)
    at triggerExitCallback (/app.asar/src/buffered-process.js:303:11)
    at /app.asar/src/buffered-process.js:316:11
    at /app.asar/src/buffered-process.js:185:9)
    at emitOne (events.js:101:20)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
```

### Commands

```
```

### Non-Core Packages

```
git-plus 7.2.2 
github 0.0.0 
language-markdown 0.19.1 
seti-syntax 1.1.2 
seti-ui 1.6.1 
slack-ui 0.8.0 
snippet-creator 0.0.0 
spotify-ui 1.2.2 
Sublime-Style-Column-Selection 1.7.3 
sublimify 0.5.0 
terminal-plus 0.14.5 
```

**Comment by as-cii** [comment]
Thanks for the report @ungb. I was unable to reproduce locally, but I analyzed the code and tried to find possible ways in which it could have thrown that exception. I discovered a potential code path that could be causing what you experienced and made an attempt at fixing it in d3dba5eb5608190ecd806cdf3743c84b3f5516a6.

Please, let me know if you are still able to reproduce. If yes, we could maybe 🍐 on Tuesday in order to debug the issue on your machine and garner data to fix it.

**Comment by Ben3eeE** [comment]
The `Open Config Folder` button does nothing when I have this PR linked. In Atom 1.15.0-beta3 it works.

**Comment by as-cii** [comment]
Thank you for the heads-up, @Ben3eeE! It should be fixed by 75e8896.

**Comment by ungb** [comment]
The issue is now fixed for me @as-cii after your latest change regarding the issue I was having installing packages.

Under Available updates I'm seeing:
Before your Change:
image


After your change:
image

I'm not sure why I'm seeing undefined exactly, but it's not related to your change.  The style changed though.

**Comment by as-cii** [comment]
> I'm not sure why I'm seeing undefined exactly, but it's not related to your change. The style changed though.

Nice find! I have fixed it in 6631f9c.

**Comment by ungb** [comment]
Looks good to me, but looks like there's a conflict.  Will look at this again after the merge conflict is resolve.

One little issue I found is if you open the list view in packages/theme/install and click on the author name, before your change it open the author page,  Now it just goes into the package.  If you click on the author name there, it goes to the author page.

image

**Comment by Ben3eeE** [comment]
Got this now. I am on 75e8896d9d10a12a0dacb399ed9a9e622d82f37b which is after the supposed fix but not latest commit.

I'll pull latest and try to reproduce it.

```
C:\Users\lineri\Desktop\issues\atom master\settings-view\lib\package-detail-view.js:108
Hide Stack Trace
Error: Failed to execute 'replaceChild' on 'Node': The node to be replaced is not a child of this node.
    at Error (native)
    at PackageDetailView.completeInitialization (package-detail-view.js:108:35)
    at PackageDetailView.loadPackage (package-detail-view.js:125:12)
    at disposables.add.packageManager.on (package-detail-view.js:383:14)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-56f55e9\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-56f55e9\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at PackageManager.module.exports.PackageManager.emitPackageEvent (file:///C:/Users/lineri/Desktop/issues/atom master/settings-view/lib/package-manager.coffee:449:14)
    at file:///C:/Users/lineri/Desktop/issues/atom master/settings-view/lib/package-manager.coffee:342:10
    at exit (file:///C:/Users/lineri/Desktop/issues/atom master/settings-view/lib/package-manager.coffee:62:7)
    at triggerExitCallback (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-56f55e9\resources\app.asar\src\buffered-process.js:265:9)
    at ChildProcess.process.on.code (C:\Users\lineri\AppData\Local\atom\app-1.16.0-dev-56f55e9\resources\app.asar\src\buffered-process.js:295:9)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

**Comment by ungb** [comment]
@Ben3eeE what were you doing when you saw this?  I couldn't repro it after the fix, I'll try again now.

**Comment by Ben3eeE** [comment]
@ungb @as-cii This is what I did to reproduce the issue.
jquery settings view install error

**Comment by as-cii** [comment]
Thank you so much for reproducing this, @Ben3eeE! I have fixed it in 480ff47: I'll go ahead and merge this pull request as soon as we get a green build.

**Pull request merged**
