### PR TITLE
Listening for enter key on search input field

### LINKED ISSUE #553: search packages can't work. only after switching to themes and return to packages
Use case:
 Open Packages -> Settings view -> Install packages, then enter some text in search field, but nothing doing.
 for get result I must change Packages button to Themes and switch again for a get search result.
 No 'Enter' key action here too

### PR DESCRIPTION
**Pull request by dijs**
Fixes #553

### CODE REVIEW

**Comment by dijs** [comment]
Is there any way to test this module locally?

**Comment by thedaniel** [comment]
A spec for this would be nice.

If you run `apm link -d` from your checkout the linked version will override the bundled on in dev mode. You might need to run `apm rebuild` as well.

**Comment by kevinsawicki** [comment]
Isn't enter already handled here: https://github.com/atom/settings-view/blob/e63a52c41342819b3b78c894a2e63f13391fbd16/lib/install-panel.coffee#L75-L76 ?

**Comment by dijs** [comment]
@kevinsawicki The search method was not being called when I pressed enter in the input field until I added this line. Possibly a OS specific issue? I am on OSX.

**Pull request closed without merging**
