### PR TITLE
Sort packages search

### PR DESCRIPTION
**Pull request by bastilian**
This implements sorting of packages based on #384.

Currently it sorts package and theme search results based on downloads count. 

screen shot 2016-04-05 at 15 07 23

screen shot 2016-04-05 at 15 06 51

### CODE REVIEW

**Comment by lee-dohm** [comment]
@simurai How do you feel about moving the version out of the metadata area and putting it next to the package name?

**Comment by simurai** [comment]
> How do you feel about moving the version out of the metadata area and putting it next to the package name?

I kinda like it. It ties the name and version more together. Maybe it could be toned down a bit or smaller font-size so it stands out a bit more from the name?

One issue with sorting by downloads is that an exact match (but not as popular) might get under lots of other popular packages. Like if you copy&pasted the name and want to install exactly that package, it would be hard to find.

screen shot 2016-06-23 at 4 00 56 pm

Not sure if it's possible to sort with multiple criterias?

Also.. if we add the stars count, it would be nice if you could star packages too. See https://github.com/atom/settings-view/issues/141

**Comment by bastilian** [comment]
Glad you like it @simurai. I'll make the version number to be smaller than the name.

Regarding the search results, I think putting an exact match as the first would make total sense and then have the following results sorted by stars. maybe even with a little bit of a gap between so the first and exact matching one sticks out even more.

Adding star and unstar to the package card shouldn't be a hard thing to do, as well as adding another list to the "Packages" pane to list your starred packages. For the "Packages" pane I would however suggest to default to collapsed lists, maybe revamp it even a little bit in the long run.

I'll style the version number better and implement the result listing.

Let me know what you think about how to add the Star-Features.

**Comment by bastilian** [comment]
hm... I think past me had a thought... I implemented it in a way that the sort can be an option to the query, what do you think about adding two buttons like packages & themes, but smaller, below them to choose the sorting and default to downloads?

**Comment by simurai** [comment]
I see, yeah. Adding the stars count would make more sense if it's also possible to sort by stars.

> list your starred packages

Would also be nice, but better to keep PRs small.

**Comment by bastilian** [comment]
> Would also be nice, but better to keep PRs small.

Totally agree. I'll open a PR based on #141 and leave the stars out of here.

I'll make the changes for the search result and update this PR.

**Comment by bastilian** [comment]
Oh, and we can add the sorting by stars in the other PR as well.

**Comment by bastilian** [comment]
Tada! 🎉 !

screen shot 2016-06-23 at 11 37 33

* the version number is now `.8em` of the package name
* Star and downloads count are now configurable on PackageCard's (defaults to showing the downloads count for now.
* An exact match is now extracted and put in front of all other results.

**Comment by 50Wliu** [comment]
> An exact match is now extracted and put in front of all other results.

:heart_eyes:

**Comment by Ben3eeE** [comment]
> An exact match is now extracted and put in front of all other results.

Does this apply to https://github.com/atom/settings-view/issues/513?

Same issue exists on the apm repo for the react package.

**Comment by bastilian** [comment]
@Ben3eeE yes, this will address #513 as well.

I just tested with the `react` package, but noticed a bug that it appears twice in the result.
Will look into this.

**Comment by bastilian** [comment]
Ok, that bug is now fixed. `react` and all other exact matches show up first now. :)

On a side note: I think this should be seen as a workaround, the actual fix should be applied to where the search is actually performed to have the same result in atom, apm and on atom.io. But this is a good testing ground to figure out how the search in general could work, what it should show as results and how they should be ordered.

**Comment by lee-dohm** [comment]
Looks good. Thanks @bastilian! :bow:

**Comment by lee-dohm** [comment]
@bastilian Is this still `[WIP]`? I tested it and it looks good ... but I didn't want to merge it unless you were done with it :grinning:

**Comment by Ben3eeE** [comment]
I tested this as well. Everything seems to be working for me. Great work @bastilian :+1:

**Comment by bastilian** [comment]
perfect. :) and it's not [WIP] anymore. :D

**Comment by lee-dohm** [comment]
Thanks for this @bastilian :grinning:

**Comment by bastilian** [comment]
YAY! Thank you for merging @lee-dohm!

**Comment by ricksterhd123** [comment]
This no longer applies today, what happened?

**Pull request merged**
