### PR TITLE
Don't render input fields for core.customFileTypes

### PR DESCRIPTION
**Pull request by maxbrunsfeld**
Fixes https://github.com/atom/settings-view/issues/670

### CODE REVIEW

**Comment by mnquintana** [comment]
Should we maybe add some test coverage for this?

**Comment by maxbrunsfeld** [comment]
Personally, I think that the settings-view as a whole could use a lot better test coverage, but I don't really think it's in scope for *this* particular change.

For a change like this, I do think it's important to add tests that fit in with the project's existing tests. But for the change in question, the existing tests are [sparse](https://github.com/atom/settings-view/blob/master/spec/settings-panel-spec.coffee#L7). They don't make assertions about individual fields in Atom's config schema that are omitted from the UI, which I actually think is fine.

In the past, I've definitely accidentally broken things in settings-view, through changes to Atom core, without seeing any test failures. I'd love to help prevent this from happening in the future, but it'll be a bigger effort, and I don't think it needs to block this PR.

**Comment by mnquintana** [comment]
Fair enough :+1:

**Comment by maxbrunsfeld** [comment]
Thanks for :eyes: for our test coverage.

**Pull request merged**
