### PR TITLE
Package card and detail view UI improvements

### PR DESCRIPTION
**Pull request by jlord**
- [x] Link to atom.io from package title
- [x] Click on body takes user to settings (detail) view
 - [x] Remove 'settings' button as that's the current view
- [x] Remove `status-indicator` on bundled un-status'ed themes
- [x] Fix disappearing breadcrumbs #358 
- [x] Show breadcrumbs on installed packages settings view
- [x] Show PackageDetailView for packages that _aren't_ installed
  - [x] PackageDetailView should change to installed state if package is installed from it
  - [x] PackageDetailView should change to uninstalled state if package is uninstalled from it
- [x] Show readme on on (future) install package detail view :point_up_2: 
 - [x] Remove readme button?

Overlaps with: #360, #351

### CODE REVIEW

**Comment by zephraph** [comment]
So clicking anywhere inside the package card besides an action item (link, button) takes you to the detail view?

**Comment by thedaniel** [comment]
@zephraph yep

**Comment by zephraph** [comment]
I haven't tired it out yet, but does that seem a little unintuitive to you? Does the whole card highlight or something on hover so the user knows that it's clickable?

I feel like making the package name link to Atom in a cases is fine. The settings button already takes the user to the package's settings, right? So, just adding a preview button on the pre-installed card view would give a consistent interface. 

It just seems weird to me that clicking an area is performing an action.

**Comment by thedaniel** [comment]
I encourage you to try it out. It didn't seem unintuitive to either of us working on it at the time.

**Comment by jlord** [comment]
> So clicking anywhere inside the package card besides an action item (link, button) takes you to the detail view?

@zephraph @thedaniel Also, the _Settings_ button will still remain. So clicking the body **or** the button will take you to the settings (detail) view. :rainbow: 

_from the Themes tab view_
screen shot 2015-02-13 at 10 55 19 am

_clicking on body or Settings button above both lead here_
screen shot 2015-02-13 at 10 55 29 am

**Comment by thedaniel** [comment]
I have <s>InstalledPackageView</s>PackageDetailView showing for all packages now, though I haven't checked it off the task list because I haven't looked at the UI in detail--in other words it probably needs to show and hide some stuff and be smart enough to update itself on packagemanager events.. but at least you can click through to it now.

**Comment by thedaniel** [comment]
:+1: on removing the README button.

Adding the README and viewing settings-view at a really large size makes me want to put the keybindings and README in a fixed-width column, which would also maybe make it possible for us to design toward @simurai's idea for putting the settings in a fixed pane in the future.. doesn't have to happen in this PR though.

**Comment by thedaniel** [comment]
Also the README is available in the API results, so we should be able to show it on any package detail view, not just installed ones. I'll take a look at that now, actually.

**Comment by thedaniel** [comment]
I think this is pretty much shippable as it contains a number of incremental and not-so-incremental improvements. It would be nice to revisit a fixed container width and perhaps some markdown styling but IMO I don't think it needs to hold this up.

**Comment by zephraph** [comment]
I'm excited!

Sorry I didn't get more involved, I've been slammed with work deadlines.

**Comment by simurai** [comment]
Tweaked the headings of the README a bit. Also, the README wrapps now and doesn't exceed the width of the details above.

**Comment by jlord** [comment]
@simurai @thedaniel :sparkles: :sparkles: :sparkles: 

Awesome, let's :ship: !

**Comment by thomasjo** [comment]
This is brilliant! :ship: :rocket:

**Comment by abe33** [comment]
Nice work, I can't wait to see it :ship:.

I noticed a small issue regarding the README handling, it seems it doesn't detect the file when it has a `md` extension. Given this the default when generating a package through apm it should be handled properly.

Also, I'm currently working in #377 on solving the installation of incompatible versions of a package. I introduced a new div in the package card to display compatibility issue message. If you have suggestion on that in prevision of the merge of both PRs. Maybe you see a better way of presenting these messages to the user?

**Comment by thedaniel** [comment]
@abe33 did you see this behavior in a package you installed from atom.io or an unpublished one that you are developing?

**Comment by abe33** [comment]
@thedaniel Oh, I think I understand now, I was looking at some of my packages to see how it render, but they are loaded as development package (I always link my packages in dev mode only so that I can install them like any other user in normal mode) and I guess you're reading the README from the denormalized `package.json`. 

Sorry to not have thought of that before. 

Now that I think about it, it could be useful to read the README file from the disk for development package. If we're willing to show it in the settings view it'ld allow developpers to preview their README in context. 
Also, a visual clue in the package card to discrimate dev packages from *installed* packages. 
It could be useful if the dev package is a package that was cloned from a fork to try things and forgotten at some point.

**Comment by thedaniel** [comment]
> Now that I think about it, it could be useful to read the README file from the disk for development package.

If we can fix this in the settings-view code (vs the atom/atom code) we should do it in this branch before merging.

> Also, a visual clue in the package card to discrimate dev packages from installed packages. 

This is important but should be a separate issue and PR IMO.

**Comment by abe33** [comment]
> If we can fix this in the settings-view code (vs the atom/atom code) we should do it in this branch before merging.

Sure, I was thinking the same way.

**Comment by jlord** [comment]
:tada:

**Pull request merged**
