### PR TITLE
Case-insensitive keybindings search. Fixes #496

### LINKED ISSUE #496: Case-insensitive keybindings search
I'm suggesting to make the keybindings search case-insensitive to get more results while searching. Aldo all commands are lowercase, there are some keystrokes that have uppercase letters.

### PR DESCRIPTION
**Pull request by jerone**
Fixes #496

### CODE REVIEW

**Comment by 50Wliu** [comment]
Could you add some specs for this please?
Also, it's `insensitive`.

**Comment by jerone** [comment]
[**@50Wliu**](https://github.com/50Wliu) commented on [6 mei 2015 21:18 CEST](https://github.com/atom/settings-view/pull/497#issuecomment-99578848 "2015-05-06T19:18:27Z - Replied by Github Comment Enhancer"):
> Could you add some specs for this please?  
> 
> Also, it's `insensitive`.

Damn dyslexia. Thanks for mentioning. :smile: 

As for the tests, I had a look at it, but it's too complicated for an edit I just did here in GitHub.

**Comment by jerone** [comment]
@50Wliu Something like this? (untested):
```
  describe "when searching key bindings", ->
    it "find case-insensitive results", ->
      keyBindings.push
        source: atom.keymaps.getUserKeymapPath(), keystrokes: 'F11', command: 'window:toggle-full-screen', selector: 'body'
      atom.keymaps.emitter.emit 'did-reload-keymap'

      panel.filterKeyBindings keyBindings, 'f11'
      
      expect(panel.keybindingRows.children().length).toBe 1
      
      row = panel.keybindingRows.children(':first')
      expect(row.find('.keystroke').text()).toBe 'F11'
      expect(row.find('.command').text()).toBe 'window:toggle-full-screen'
      expect(row.find('.source').text()).toBe 'Core'
      expect(row.find('.selector').text()).toBe 'body'
```

**Comment by 50Wliu** [comment]
Seems ok to me, but I'm not that proficient in Coffeescript.
@atom/feedback does this look good to you? :eyes:

**Comment by kevinsawicki** [comment]
> does this look good to you?

Yeah, that looks good to me.

**Comment by jerone** [comment]
Test added, and [All is well](https://travis-ci.org/atom/settings-view/builds/61536405).

**Comment by thedaniel** [comment]
thanks!

**Pull request merged**
