### PR TITLE
Fix 100% CPU use on startup. Fixes #555 for me.

### LINKED ISSUE #555: Atom 1.0 will consume 100% CPU when managing packages
_From @lovio on June 26, 2015 6:7_

No matter installing or uninstalling packages, `Atom Helper` will comsume over 100% CPU.

_Copied from original issue: atom/atom#7438_

### PR DESCRIPTION
**Pull request by LegNeato**
This was causing a 100% cpu spike on launch with many packages (like Nuclide). Completely fixed my `Atom Helper` CPU issues on launch!

### CODE REVIEW

**Comment by LegNeato** [comment]
Note: I still get 100% CPU when viewing packages in the settings view.

**Comment by thedaniel** [comment]
This looks good to me.

**Comment by dorongutman** [comment]
Can you please release an new version of atom now that this is fixes ? It's impossible to work with atom like this!!

**Comment by nathansobo** [comment]
@dorongutman We should have a new beta out this week.

**Pull request merged**
