### PR TITLE
Update README.md and LICENSE.md

### PR DESCRIPTION
**Pull request by torn4dom4n**

### CODE REVIEW

**Comment by 50Wliu** [comment]
Thanks!

**Comment by damieng** [comment]
Copyrights are supposed to retain the oldest original date btw.

**Comment by 50Wliu** [comment]
> Copyrights are supposed to retain the oldest original date btw.

I wasn't sure about that, so I checked atom/atom's LICENSE, which had a similar PR accepted to change the year to 2016.

**Comment by damieng** [comment]
We should probably correct both of them.  The US copyright.gov site says "The year of first publication. " http://www.copyright.gov/circs/circ03.pdf

**Comment by 50Wliu** [comment]
Done.  Thanks for the clarification!

**Comment by torn4dom4n** [comment]
I don't know about that. Sorry!

**Pull request merged**
