### PR TITLE
Escape CSON correctly

### PR DESCRIPTION
**Pull request by Aerijo**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

Escapes quotes and backslashes better in the keybinding-to-string function.

In addition to linked issue, this is a keybinding I found on my own Atom that needs quote escaping
```cson
'atom-text-editor[data-grammar~=\'css\']':
  'ctrl-alt-c': 'css-declaration-sorter:sort'
```
Without this PR, it wouldn't escape the value quotes.

Also tidied up the composition part, which was really hard to read IMO. Now it's a clean single line with well defined newlines and spacing.

### Alternate Designs

Considered `CSON.stringify(...)`, but 
(1) it does a lot of extra work for little benefit, 
(2) it returns with double quotes, and 
(3) ~~[it's wrong](https://github.com/groupon/cson-parser/blob/15bfd9695c79b627bd4dd7aabe1a4cc925a42494/lib/stringify.js#L80); trying that with the raw text `\\"` (escaped backslash + `"`) ironically gives `\"`, which is an escaped `"`.~~ (Actually might not be wrong, as `\\"` would already be escaped by `JSON.stringify` to `\\\"`. But I don't want to add a new dependency just for one thing) 

Could also run `JSON.stringify` and then swap quote escapes + replace single with double quotes, but I don't think it's necessary.

### Benefits

Correctly escape `'`, `"`, and `\` in strings

### Possible Drawbacks

none

### Applicable Issues

closes https://github.com/atom/settings-view/issues/1110

### CODE REVIEW

**Comment by rsese** [comment]
Almost forget to ask, can you add a test for this?  Whoever ends up reviewing will ask :smile:

**Comment by Aerijo** [comment]
@rsese added specs

**Comment by rafeca** [comment]
Thanks for the contribution! 😍

Since the escape logic of CSON [matches the one in JSON](https://github.com/lifthrasiir/cson#brief-introduction) (with the only difference of having to escape single quotes instead of double quotes when using single quote notation), it will be easier to just use `JSON.stringify()` and change the quoting escaping.

Your `escapeCSON` function would look like:

```js
const escapeCSON = (input) => {
  return JSON.stringify(input)
    .slice(1, -1) // Remove wrapping double quotes
    .replace(/\\"/g, '"') // Unescape double quotes
    .replace(/'/g, '\\\''); // Escape single quotes
}
```

This will also help escaping other reserved characters like `\n`, etc.

What do you think?

**Comment by Aerijo** [comment]
Yeah, it feels safer to leave the majority of the escaping to the builtin JSON.

@rafeca Done, and the failed spec seems completely unrelated.

**Pull request merged**
