### PR TITLE
Focus search fields in installed themes and packages panels

### LINKED ISSUE #440: Focus search field after openning install package / theme screen
Hi :),

how about to focusing search field after opening Settings View: install screen? Right now I have to double tab to get there.

### PR DESCRIPTION
**Pull request by mnquintana**
This PR makes it so that the Packages and Themes panels correctly autofocus when clicking on them within settings-view. (#432 will come in another PR.)

(Should I write specs for this?)

### CODE REVIEW

**Comment by thomasjo** [comment]
> Should I write specs for this?

That would be great as it will insulate us from future regressions. Thanks for fixing this by the way!

**Comment by mnquintana** [comment]
@thomasjo No problem! Although maybe you can help with this - I'm having trouble figuring out how to simulate navigating to a panel. Any ideas?

**Comment by thomasjo** [comment]
There are two easy ways to comes to mind; first is to do e.g.

``` coffee
atom.workspace.open('atom://config/packages')
```

Alternative is to issue a command that triggers basically the same `open` invocation. E.g. `settings-view:uninstall-packages` and similar.

**Comment by mnquintana** [comment]
@thomasjo I don't think that'll work in this case because of #432 (so the test will always fail until #432 is resolved, which I could look into as part of this PR)

@thedaniel Any ideas for simulating navigating to a panel?

**Comment by thomasjo** [comment]
> I don't think that'll work in this case because of #432 

If you don't want to test this in an "end-to-end" fashion, you should be able to leverage [`SettingsView::showPanel`](https://github.com/atom/settings-view/blob/a314e02734ac761c8b86b3af22ba2f506fb0dca0/lib/settings-view.coffee#L166).

**Comment by thomasjo** [comment]
> until #432 is resolved, which I could look into as part of this PR

That would be great, assuming the problem can be fixed in this package.

**Comment by mnquintana** [comment]
@thomasjo @thedaniel Since #432 is a bigger issue than I thought (see https://github.com/atom/settings-view/issues/432#issuecomment-85243483)), I'd much rather work on it in a separate PR. This does resolve #440 though and makes #394 possible, which I'm also working on. What do you think?

**Comment by thomasjo** [comment]
Sounds good to me. I'll let @thedaniel have the final word.

**Comment by thedaniel** [comment]
@mnquintana yep, sounds good.

**Comment by thedaniel** [comment]
To clarify, you want to merge this as it stands now and do further work on top of it in the other PRs right?

**Comment by mnquintana** [comment]
@thedaniel Yup!

**Comment by thedaniel** [comment]
This doesn't seem to fix #440 for me.

```
[settings-view (master)⚡]> git checkout mnquintana/focus-filters 
Note: checking out 'mnquintana/focus-filters'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at e4774c1... WIP: Add spec for search filter focus
2015-04-03 14:55:40
[settings-view]> apm link -d
/Users/daniel/.atom/dev/packages/settings-view -> /Users/daniel/atom/settings-view
2015-04-03 14:57:51
[settings-view]> atom -d
```

In the opened window, I run "settings view: install packages and themes" and the search field is not focused.

**Comment by mnquintana** [comment]
@thedaniel You're right, I had been misinterpreting #440 this whole time – it actually is a duplicate of #432. So this resolves an unreported issue, namely, that the Packages and Themes panels didn't autofocus even when clicking on them. I'll update the main PR body to reflect that.

What do you think now?

**Pull request merged**
