### PR TITLE
Add link to package name

### PR DESCRIPTION
**Pull request by zephraph**
Fix for #328.

### CODE REVIEW

**Comment by thedaniel** [comment]
This view is used in a lot of different places, including list views. If we have this href set everywhere, if you click a package name in a list of packages, it will *both* open your browser and navigate within settings view to a package detail page (InstalledPackageView).

screen shot 2015-01-21 at 6 11 13 pm

I think a better thing to do would be to detect whether the AvailablePackageView is inside an InstalledPackatgeView or initialize it with a flag, and have a conditional in the click hander: https://github.com/atom/settings-view/blob/808cd73d72b98dab83ca1ee139f967cffc47cd43/lib/available-package-view.coffee#L76

**Comment by zephraph** [comment]
All right, I'll try that out

**Comment by zephraph** [comment]
I looked at a few different options. Checking if the available package view was inside the installed package view wasn't enough. Because the install view now shows already installed packages as well as packages not installed yet. The common link here is whether or not the package is installed. 

I made the simplest changed possible: check if the install button is visible. If it is, open the external link. If not, open the package view. I realize this may not be the "best" way to do it. 

An alternative would be to add a flag on the different events (when installing, installed, uninstalled, etc) that would determine how the on package name clicked event was handled. That would decouple the traversal from the visibility of the install button, but it would also add more code. 

If you would rather that method let me know and I can implement it. If you would rather a different method then I'm all ears. I'd just really like to get this fixed. It's a feature I used a lot in the older versions.

**Comment by zephraph** [comment]
@thedaniel, would you mind reviewing this when you get the chance? Thanks!

**Comment by thedaniel** [comment]
I've changed my mind on this - I think it's potentially confusing to have the same control in the same context (package card) have two different actions. Consistency is a virtue in UI. If it's important to visit Atom.io from the card we should add another element, perhaps an octicon next to the package name, something else in the button row, etc. 

cc @simurai in case he has any UI ideas.

Sorry that I encouraged you to implement this and then rejected it -- I guess I needed to stew on it a bit more.

**Comment by thedaniel** [comment]
Also, for what it's worth I do think we should support easily opening atom.io from the card because the metadata there is probably always going to be a few revisions ahead of the settings view in terms of completeness etc.

**Comment by thedaniel** [comment]
We could also consider trying to have some kind of visual consistency around what controls open the browser and what causes the settings view to navigate somewhere.. given that the package name and the author are both normally styled links but do two different things.

**Comment by zephraph** [comment]
I was simply trying to match the functionality that use to be there. 

It isn't even that important to pull up atom.io from the card. I just expect to be able to click on the package title and get more information about that package so I can decide whether or not to install said package. 

Right now I have to open atom.io manually and look up the package. If you want consistency, what about creating another view that renders the README.md in a view similar to the single package view. 

Here's an example mockup:
picker

This is consistent with the current implementation and doesn't add clutter to the package cards. It also gives the users the ability to see what the package actually does. 

What do you think @thedaniel?

**Comment by simurai** [comment]
Showing the `README.md` would be an option. Or do this:

1. Remove the underline on `:hover` of package names. So that it doesn't look like you can click it.
2. Add a "View on Atom.io" button infront of the "Install" button. It's the same as in the bottom row of a package detail page. Like this:

screen shot 2015-01-28 at 2 05 37 pm

**Comment by thedaniel** [comment]
I'm down to show the README in any case outside of a link solution, it just wasn't a big priority for me right now. Happy to accept a PR and/or put it on the ol' todo list though. 

--
Daniel Hengeveld
(sent from my phone)
http://about.me/thedaniel

**Comment by simurai** [comment]
I'm not sure about "show the README" inside the card in the package settings, like in the above mockup. I think that page should only be accessed after installing. But there could be a README button that would open a new tab. Like this:

screen shot 2015-01-28 at 5 33 54 pm

screen shot 2015-01-28 at 5 42 14 pm

Note that the screenshot is taken with a theme that styles the `markdown-preview` package. Most themes will have a white background.

So yeah.. I would say either:

1. the external "View on Atom.io" link
2. or "README" as a new tab

@zephraph Any preferences? My vote tends to go to the external "View on Atom.io" link.

**Comment by zephraph** [comment]
Well, there are positives and negatives to both approaches. 

First off, your alternatives are more concise and I like that. The issue is just taking that approach _alone_ makes for interface inconsistencies of its own. When I install the package, the name is clickable. It does something... but when I don't have it installed the package name does nothing? It's slightly confusing because the views are essentially the same just with different buttons visible. So one approach would be to completely make the package name non-clickable. Technically the settings button is there so it's really redundant functionality, right?

So my position is this. If it's clickable, it takes you to a new view which is essentially what I mocked up. The thing about that is though, that's not the settings view. It'd be a new "package preview" view or something. Some of the links that are listed on there are definitely unnecessary but I left them in there because I was lazy. Point is, this isn't the settings view, just a view to provide information about the package and a quick way to navigate to all the important stuff related to the package. One of the biggest reasons I like this is because it gives consistent behavior between viewing an already installed package and a not-yet-installed package _and_ it doesn't open an external browser. 

As a retort to myself this will take longer to implement and it's not necessarily as visible as clicking an 'Open on Atom.io' button as @simurai mocked up. Plus it would mostly eliminate the need for anyone to use atom.io/packages if they had Atom installed. That being said, using something for the sake of using it really isn't a good design practice. 

I really like clickable packages names though. It's all about how close the package name is to the settings-view navigation. Removing it isn't a deal breaker, but I still prefer having the option to use it. 

So here are the options as I see it

Option 1:
Completely disable clickable package names on all views and add the open on atom.io button

Option 2:
Add a package preview view and have that open when clicking on an uninstalled package

Option 3:
Do option 2 + add the atom.io button. 

@thedaniel, @simurai thoughts comments?

**Comment by mnquintana** [comment]
This is sort of related to #330, #328, but a few random thoughts in no particular order:
- Links that open in a browser (external links) should have some kind of visual indicator so you know what to expect whenever you click a UI component in settings-view - this might help mitigate expectations for users who click the package name and expect to be taken to atom.io
- I agree that there really isn't an easy way to get to atom.io/packages/<package-name> in the package card, which seems to be more of an issue when you're in the Install pane
  - This also seems to beg the question, how much of your package research / updating / installation workflow should be spent in Atom, and how much on atom.io? Personally, I think too much context-switching is a Bad Thing, and can much too easily break your flow, so I'd be in favor of having to bounce to atom.io as infrequently as possible.
- I like the idea of having a "View on Atom.io" link, but it seems really obtrusive as a button like that next to Install. I feel like I'd rather it be a clearly-defined icon or something (maybe with a tooltip on hover) next to the package name.
- I really like clickable package names too, and I think they should stay the way they are more or less (pretty much necessary for #355)
- It seems to me like "Install cards" have different use cases than installed package cards - for instance, if you're in the Install pane and looking at a package, you probably want to learn more about it, hence an easy way to get to the README seems important.
- @zephraph I think I like option 3 the most, as long as the atom.io button is less obtrusive. Otherwise, option 2, although that would be a lot more work.

**Comment by simurai** [comment]
> @zephraph that's not the settings view. It'd be a new "package preview" view

It would look similar, but only have the things that make sense. ok, yeah.. I see.

Option 1, 2 and 3 could also be done in steps. Meaning do option 1 as a first step, since there is less effort involved and would already improve the current state. Then once that is launched, we can see how option 2 would work out and then decide about keeping the "Open on Atom.io" button or not (option 3).

**Comment by mnquintana** [comment]
@simurai The only issue with option 1 is that it would make #355 impossible :confused:

**Comment by simurai** [comment]
> @mnquintana This also seems to beg the question, how much of your package research / updating / installation workflow should be spent in Atom, and how much on atom.io?

If it's possible to hack an "Install" button onto atom.io, that would be amazing. Doing discovery inside Atom is ok too, but you can't easily share or link to a package.

> I like the idea of having a "View on Atom.io" link, but it seems really obtrusive as a button like that next to Install. I feel like I'd rather it be a clearly-defined icon or something (maybe with a tooltip on hover) next to the package name.

Hmm.. I probably would find an icon next to the package name a bit obtrusive. I know, there is the "external link" issue again #330 :innocent: But as a button group the two actions would be together. Like a cross-road: "Do you want more infos or go ahead and install it?"

**Comment by simurai** [comment]
> The only issue with option 1 is that it would make #355 impossible :confused:

Hmm.. yeah. Well, option 1 could also be done by keeping the name clickable and just "disable" it for uninstalled cards. Let's call it 1B. Personally I think clicking the name is somewhat a hidden feature. More like a shortcut if you know about it, but not the obvious way I would expect the settings to be found.

**Comment by zephraph** [comment]
> If it's possible to hack an "Install" button onto atom.io, that would be amazing.

I really like this and I'd love to discuss it more, but I think it's outside the scope of this PR. The scope of this issue has changed enough that I feel like I should go ahead and close this PR. I'm going to hash out option 2 this weekend and submit a new PR. Then, after everyone's had a chance to play with it, we'll come back to this discussion.

**Comment by simurai** [comment]
> I'm going to hash out option 2 this weekend and submit a new PR.

Great. Let me know if you need some help with styling.

Just in case and maybe as a quick fix for the current situation, I made a PR for option 1B (still needs specs): #360

**Comment by mnquintana** [comment]
> @simurai: Personally I think clicking the name is somewhat a hidden feature. More like a shortcut if you know about it, but not the obvious way I would expect the settings to be found.

Too bad we don't have any data about that – looks like [metrics wouldn't know](https://github.com/atom/metrics#collected-data).

> Hmm.. I probably would find an icon next to the package name a bit obtrusive. I know, there is the "external link" issue again #330 :innocent: But as a button group the two actions would be together. Like a cross-road: "Do you want more infos or go ahead and install it?"

Heh fair enough :stuck_out_tongue_closed_eyes:, it was only a half-baked idea. That's a good point about it being a crossroad – I think my brain is just not used to seeing another button there (with so many words) so I'll just give it time.

**Comment by thedaniel** [comment]
> If it's possible to hack an "Install" button onto atom.io, that would be amazing.

This is a thing that has been an open item on atom/atom for a while. The latest version of the issue is here: https://github.com/atom/atom/issues/5262

I'd personally like to get it in sooner rather than later but the 1.0 feature list is already quite large so it unfortunately is scheduled for "when someone has time to get to it".

> I really like this and I'd love to discuss it more, but I think it's outside the scope of this PR. 

This is correct.

**Comment by thedaniel** [comment]
> [clicking the package name is ] more like a shortcut if you know about it, but not the obvious way I would expect the settings to be found.

Maybe my perspective is tainted because I implemented it, but to me clicking on the name or the card body *is* the obvious way to navigate forward.

**Comment by zephraph** [comment]
@thedaniel I kinda agree. It's intuitive to me to interact with the package card in that way.

**Comment by mnquintana** [comment]
@thedaniel I agree too. I actually would expect the settings button to jump you to the Settings section of the package detail view (like a `/#something` link).

**Comment by simurai** [comment]
There is also #284. Having all package settings under the main "settings" menu.

Then the current "package settings" page is not needed and could be replaced by the "package preview" page. Or it would be more like "package info". So clicking on the "Settings" button would go to `settings/#package-name` and clicking on the name would go `packages/#package-name`.

**Comment by thedaniel** [comment]
I don't know how I feel about removing the package settings from the detail page even if they are all on the main settings page as well..

**Comment by simurai** [comment]
Ohh.. wait. I agree, better to keep it in both places. I forgot about the keybinds of packages.

**Comment by thedaniel** [comment]
@simurai @zephraph I started a PR with @jlord trying to pull in all of the UI considerations around the package card in #373 - I think we can address this PR as well as #360 in one holistic attempt.

**Pull request closed without merging**
